homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

  packages: !include_dir_named packages

  customize: !include customize.yaml

group: !include groups.yaml

logger:
    default: warn
    logs:
        homeassistant.components.history: debug
        homeassistant.components.recorder: debug
        # homeassistant.components.isy994: debug
        # custom_components.isy994: debug
        netdisco.ssdp: error

# Enables the frontend
frontend:
map:

# Enable the Configuration panel
config:

cloud:
  alexa:
    filter:
      include_entities:
        - media_player.home_theater
        - switch.nintendo_switch
      include_domains:
        - none
    entity_config:
      media_player.home_theater:
        name: TV
        description: The home theater in the family room
      switch.nintendo_switch:
        name: Nintendo Switch
        description: Nintendo Switch on the  Home Theater

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  # server_port: !secret http_server_port
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  cors_allowed_origins:
    - http://hassio:7080

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Needed for iOS to support location and push notifications
zeroconf:

# Allow iOS app
ios:

# Track the sun
sun:


# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# device_tracker owntracks:
#   - platform: owntracks
#     max_gps_accuracy: 200
#     waypoints: True
#     waypoint_whitelist:
#       - greg

sensor steam:
  - platform: steam_online
    api_key: !secret steam_api_key
    accounts:
      - 76561197970767347

sensor dark sky:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      # - summary
      - icon
      # - nearest_storm_distance
      # - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      # - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      # - humidity
      # - pressure
      # - visibility
      # - ozone
      # - minutely_summary
      # - hourly_summary
      # - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max

# Text to speech
tts:
  - platform: amazon_polly
    name: AWS Polly Joanna
    aws_access_key_id: !secret amazon_aws_access_id
    aws_secret_access_key: !secret amazon_aws_secret_key
    region_name: 'us-west-2'
    voice: Joanna

  # - platform: amazon_polly
  #   name: AWS Polly Justin
  #   aws_access_key_id: !secret amazon_aws_access_id
  #   aws_secret_access_key: !secret amazon_aws_secret_key
  #   region_name: 'us-west-2'
  #   voice: Justin
    
  # - platform: amazon_polly
  #   name: AWS Polly Matthew
  #   aws_access_key_id: !secret amazon_aws_access_id
  #   aws_secret_access_key: !secret amazon_aws_secret_key
  #   region_name: 'us-west-2'
  #   voice: Matthew

  # - platform: amazon_polly
  #   name: AWS Polly Brian
  #   aws_access_key_id: !secret amazon_aws_access_id
  #   aws_secret_access_key: !secret amazon_aws_secret_key
  #   region_name: 'us-west-2'
  #   voice: Brian

isy994: !secret isy994

# device_tracker: !secret device_tracker_unifi

media_player:
  - platform: squeezebox
    name: Squeezebox
    host: 192.168.0.158

# sensor sonarr:
#   - platform: sonarr
#     api_key: !secret sonarr_api_key
#     host: !secret sonarr_host
#     port: !secret sonarr_port
#     monitored_conditions:
#       - upcoming
#       - diskspace

#################
## Automations ##
#################

automation humidity:
  - alias: Humidifier Off
    trigger:
      platform: numeric_state
      entity_id: sensor.finns_room_multisensor_relative_humidity
      above: 69
    action:
      service: homeassistant.turn_off
      entity_id: switch.bedroom_electronics_outlet_switch
  - alias: Humidifier On
    trigger:
      platform: numeric_state
      entity_id: sensor.finns_room_multisensor_relative_humidity
      below: 65
    action:
      service: homeassistant.turn_on
      entity_id: switch.bedroom_electronics_outlet_switch

automation notifications:
  # ##################
  # Notifications
  # ##################
  - alias: Welcome Greg home with a notification
    trigger:
      platform: zone
      entity_id: device_tracker.greg_iphone
      zone: zone.home
      event: enter
    action:
      service: notify.pushover
      data_template:
        title: "Welcome home!"
        message: "Welcome home, Greg."

automation movie lights:
  # ##################
  # Movie Lights
  # ##################
  - alias: Movie Lights - Play
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'playing'
    condition:
      condition: template
      value_template: "{{ trigger.to_state.attributes.media_content_type == 'movie' }}"
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.movie_lights

  - alias: Movie Lights - Pause
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      from: 'playing'
      to: 'paused'
    condition:
      condition: template
      value_template: "{{ trigger.to_state.attributes.media_content_type == 'movie' }}"
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.pause_movie_lights

  - alias: Movie Lights - Stop
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'idle'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.from_state.attributes.media_content_type == 'movie' }}"
        - condition: template
          value_template: "{{ switch.movie_lights.state == 'on' }}"
    action:
      service: homeassistant.turn_off
      entity_id:
        - switch.movie_lights

automation bedroom wakeup:
  # ##################
  # Bedroom Wakeup
  # ##################
  - alias: Turn on Bedroom Lights in Morning
    trigger:
      platform: time
      at: '07:10:00'
    action:
      - service: switch.turn_on
        entity_id: switch.bedroom_wakeup_lights
