sensor.audio_rack_outlet_voltage:
  ignored: true
  polling_intensity: 0
sensor.audio_rack_outlet_current:
  ignored: true
  polling_intensity: 0
sensor.audio_rack_outlet_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.bedroom_electronics_outlet_voltage:
  ignored: true
  polling_intensity: 0
sensor.bedroom_electronics_outlet_current:
  ignored: true
  polling_intensity: 0
sensor.bedroom_electronics_outlet_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.gregs_desk_outlet_voltage:
  ignored: true
  polling_intensity: 0
sensor.gregs_desk_outlet_current:
  ignored: true
  polling_intensity: 0
sensor.gregs_desk_outlet_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.server_rack_outlet_voltage:
  ignored: true
  polling_intensity: 0
sensor.server_rack_outlet_current:
  ignored: true
  polling_intensity: 0
sensor.server_rack_outlet_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.television_outlet_voltage:
  ignored: true
  polling_intensity: 0
sensor.television_outlet_current:
  ignored: true
  polling_intensity: 0
sensor.television_outlet_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.washer_switch_voltage:
  ignored: true
  polling_intensity: 0
sensor.washer_switch_current:
  ignored: true
  polling_intensity: 0
sensor.washer_switch_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.dryer_switch_voltage:
  ignored: true
  polling_intensity: 0
sensor.dryer_switch_current:
  ignored: true
  polling_intensity: 0
sensor.dryer_switch_previous_reading:
  ignored: true
  polling_intensity: 0
