## Away Mode automations
## 
## Automations that control when Away Mode is active are all in `house_modes.yaml`. This package is just for things that are triggered BY away mode.
##
## Turns off all appropriate devices when the house enters away mode

automation:
  - alias: Turn off devices when house enters away mode
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: away
    action:
      - service: homeassistant.turn_off
        entity_id: group.lights
