###########################
## CLIMATE               ##
###########################

sensor:
  - platform: template
    sensors:
      living_room_temp_diff:
        value_template: '{{ float(states.sensor.living_room_multisensor_temperature.state) - float(states.sensor.dark_sky_temperature.state) }}'
        friendly_name: 'Indoor Temp Diff'
        unit_of_measurement: '°F'
      nursery_temp_diff:
        value_template: '{{ float(states.sensor.finns_room_multisensor_temperature.state) - float(states.sensor.dark_sky_temperature.state) }}'
        friendly_name: 'Nursery Temp Diff'
        unit_of_measurement: '°F'
