###########################
## HOME THEATER CONTROLS ##
###########################

media_player:
  platform: universal
  name: Home Theater
  children:
    - media_player.greg_s_mac_mini
  commands:
    turn_on:
      service: script.home_theater_turn_on
    turn_off:
      service: script.home_theater_turn_off
    select_source:
      service: script.home_theater_input_switch
      data_template:
        source: "{{source}}"
  attributes:
    source_list: input_select.home_theater_activities|options
    source: input_select.home_theater_activities
    state: switch.receiver_power

input_select:
  home_theater_activities:
    name: Home Theater Activities
    options:
      - none
      - plex
      - firetv
    initial: none
    icon: mdi:television

# Scripts to handle sequences of IR commands
script:
  home_theater_turn_on:
    alias: Turn on Home Theater
    sequence:
      - service: switch.turn_on
        entity_id: switch.tv_power
      - delay:
          seconds: 1
      - service: switch.turn_on
        entity_id: switch.receiver_power

  home_theater_turn_off:
    alias: Turn off Home Theater
    sequence:
      - service: switch.turn_off
        entity_id: switch.tv_power
      - delay:
          seconds: 2
      - service: switch.turn_off
        entity_id: switch.receiver_power

  home_theater_input_switch:
    alias: Change Home Theater Input
    sequence:
      - service_template: script.turn_on
        data_template:
          entity_id: >
            script.home_theater_input_{{source}}

  home_theater_input_plex:
    alias: Home Theater Input Plex
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_theater_activities
          option: 'plex'
      - service: switch.turn_on
        entity_id: switch.htpc_launch_plex
      - delay:
          seconds: 1
      - service: switch.turn_on
        entity_id: switch.receiver_input_plex

  home_theater_input_firetv:
    alias: Home Theater Input Fire TV
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_theater_activities
          option: 'firetv'
      - delay:
          seconds: 1
      - service: switch.turn_on
        entity_id: switch.receiver_input_fire_tv

  home_theater_input_none:
    alias: Home Theater Input None
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_theater_activities
          option: 'none'



automation:
  - alias: Turn on Home Theater when Plex media starts
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'playing'
    condition:
      condition: state
      entity_id: media_player.home_theater
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: media_player.home_theater
      - service: media_player.select_source
        entity_id: media_player.home_theater
        data:
          source: 'plex'

  - alias: Turn off Home Theater when Plex has been idle
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'idle'
      for:
        minutes: 30
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.home_theater
          state: 'on'
        - condition: template
          value_template: '{{ not is_state_attr("media_player.greg_s_mac_mini", "source", "plex") }}'
    action:
      - service: homeassistant.turn_off
        entity_id: media_player.home_theater

  - alias: Turn on Home Theater when Spotify casts to Fire TV
    trigger:
      platform: template
      value_template: '{{ is_state_attr("media_player.spotify", "source", "Amazon FireTV Stick") }}'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.home_theater
          state: 'off'
        - condition: template
          value_template: '{{ not is_state_attr("media_player.home_theater", "source", "firetv") }}'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - media_player.home_theater
      - service: media_player.select_source
        entity_id:
          - media_player.home_theater
        data:
          source: 'firetv'

  - alias: Turn off Home Theater when Spotify stops casting to Fire TV
    trigger:
      platform: template
      value_template: '{{ not is_state_attr("media_player.spotify", "source", "Amazon FireTV Stick") }}'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.home_theater
          state: 'on'
        - condition: template
          value_template: '{{ is_state_attr("media_player.home_theater", "source", "firetv") }}'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - media_player.home_theater

