###########################
## HOME THEATER CONTROLS ##
###########################

remote:
  - platform: harmony
    name: Living Room
    activity: SHIELD TV

homeassistant:
  customize:
    remote.living_room:
      friendly_name: Living Room Harmony Hub
    media_player.shield:
      friendly_name: Shield Google Cast

sensor:
  - platform: template
    sensors:
      spotify_output:
        friendly_name: "Spotify Output"
        entity_id: media_player.cailins_spotify
        value_template: "{{ states.media_player.cailins_spotify.attributes.source }}"

binary_sensor:
  - platform: template
    sensors:
      spotify_output_to_shield:
        friendly_name: "Spotify Outputting to SHIELD"
        entity_id: sensor.spotify_output
        value_template: "{{ is_state('sensor.spotify_output', 'SHIELD') }}"

switch:
  - platform: template
    switches:
      nintendo_switch:
        friendly_name: Nintendo Switch
        value_template: '{{ is_state_attr("media_player.home_theater", "source", "Nintendo Switch") }}'
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: "Nintendo Switch"
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.home_theater
      
media_player:
  - platform: plex

  # - platform: spotify
  #   name: Cailin's Spotify
  #   client_id: !secret spotify_client_id_cailin
  #   client_secret: !secret spotify_client_secret_cailin

  - platform: universal
    name: Home Theater
    children:
      - media_player.shield_android_tv
      - media_player.m2pserver
      - media_player.shield
    commands:
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
      volume_up:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: VolumeUp
          device: 48828020
      volume_down:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: VolumeDown
          device: 48828020
      volume_mute:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: Mute
          device: 48828020
      select_source:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: "{{source}}"
    attributes:
      source_list: input_select.home_theater_activities|options
      source: remote.living_room|current_activity
      state: remote.living_room

input_select:
  home_theater_activities:
    name: Home Theater Activities
    options:
      - SHIELD TV
      - Nintendo Switch
      - Music
      - Play PS3
      - Watch PC
      - Thursday Knights
    initial: SHIELD TV
    icon: mdi:television

automation:
  ## GENERAL AUTOMATIONS
  - alias: Turn off Home Theater when TV turns off
    trigger:
      - platform: state
        entity_id: sensor.television_outlet_power
        to: '0.0'
        for:
          minutes: 5
    condition:
      - condition: and
        conditions:
        - condition: template
          value_template: "{{ states.media_player.home_theater.state != 'off' }}"
        - condition: template
          value_template: '{{ not is_state_attr("media_player.home_theater", "source", "Music") }}'
    action:
      - service: homeassistant.turn_off
        entity_id: media_player.home_theater

  ## BIAS LIGHTING
  - alias: Turn on bias lighting when TV is on
    trigger:
      - platform: state
        entity_id: media_player.home_theater
        from: 'off'
      - platform: state
        entity_id: sun.sun
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: template
          value_template: "{{ states.media_player.home_theater.state != 'off' }}"
    action:
      - service: light.turn_on
        entity_id: light.tv_backlight
        data:
          kelvin: 6500
          brightness_pct: 100

  - alias: Turn off bias lighting when TV is off
    trigger:
      platform: state
      entity_id: media_player.home_theater
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.tv_backlight


  ## AUTOMATIC PLEX ACTIVITIES
  - alias: Turn on Home Theater when Plex media starts
    trigger:
      platform: state
      entity_id: media_player.shield_android_tv
      to: 'playing'
    condition:
      condition: state
      entity_id: media_player.home_theater
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: media_player.home_theater

  ## AUTOMATIC SQUEEZEPLAYER ACTIVITIES
  - alias: Turn on Home Theater with Squeezeplayer
    trigger:
      - platform: state
        entity_id: media_player.m2pserver
        from: 'off' # Match on, playing, paused, etc
    condition:
      condition: state
      entity_id: media_player.home_theater
      state: 'off'
    action:
      - service: media_player.select_source
        entity_id:
          - media_player.home_theater
        data:
          source: 'Music'

  - alias: Turn off Home Theater with Squeezeplayer
    trigger:
      - platform: state
        entity_id: media_player.m2pserver
        to: 'off'
    condition:
      condition: template
      value_template: '{{ is_state_attr("media_player.home_theater", "source", "Music") }}'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - media_player.home_theater

  - alias: Turn off Squeezeplayer with Home Theater
    trigger:
      - platform: state
        entity_id: media_player.home_theater
        to: 'off'
      - platform: template
        value_template: '{{ not is_state_attr("media_player.home_theater", "source", "Music") }}'
    condition:
      condition: template
      value_template: "{{ states.media_player.m2pserver.state != 'off' }}"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - media_player.m2pserver

  - alias: Turn off Family Room Squeezeplayer when idle
    trigger:
      - platform: state
        entity_id: media_player.m2pserver
        to: 'paused'
        for:
          minutes: 5
    action:
      - service: homeassistant.turn_off
        entity_id: media_player.m2pserver
