###########################
## HOME THEATER CONTROLS ##
###########################

remote:
  - platform: harmony
    name: Living Room
    scan_interval: 5
    activity: 29304816

homeassistant:
  customize:
    remote.living_room:
      friendly_name: Living Room Harmony Hub

sensor:
  - platform: template
    sensors:
      spotify_output:
        friendly_name: "Spotify Output"
        entity_id: media_player.spotify
        value_template: "{{ states.media_player.spotify.attributes.source }}"

binary_sensor:
  - platform: template
    sensors:
      spotify_output_to_firetv:
        friendly_name: "Spotify Outputting to FireTV"
        entity_id: sensor.spotify_output
        value_template: "{{ is_state('sensor.spotify_output', 'Amazon FireTV Stick') }}"

      
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

  - platform: universal
    name: Home Theater
    children:
      - media_player.greg_s_mac_mini
    commands:
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
      turn_off:
        service: remote.turn_off
        entity_id: remote.living_room
      volume_up:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: VolumeUp
          device: 48828020
      volume_down:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: VolumeDown
          device: 48828020
      volume_mute:
        service: remote.send_command
        entity_id: remote.living_room
        data:
          command: Mute
          device: 48828020
      select_source:
        service: remote.turn_on
        data_template:
          entity_id: remote.living_room
          activity: "{{source}}"
    attributes:
      source_list: input_select.home_theater_activities|options
      source: remote.living_room|current_activity
      state: remote.living_room

input_select:
  home_theater_activities:
    name: Home Theater Activities
    options:
      - Watch Plex
      - Watch Fire TV
      - Listen to Music
    initial: Watch Plex
    icon: mdi:television

automation:
  - alias: Turn on bias lighting when TV is on
    trigger:
      - platform: state
        entity_id: media_player.home_theater
        from: 'off'
      - platform: state
        entity_id: sun.sun
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: template
          value_template: "{{ states.media_player.home_theater.state != 'off' }}"
    action:
      - service: light.turn_on
        entity_id: light.tv_backlight
        data:
          kelvin: 6500
          brightness_pct: 100

  - alias: Turn off bias lighting when TV is off
    trigger:
      platform: state
      entity_id: media_player.home_theater
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.tv_backlight


  ## AUTOMATIC PLEX ACTIVITIES
  - alias: Turn on Home Theater when Plex media starts
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'playing'
    condition:
      condition: state
      entity_id: media_player.home_theater
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: media_player.home_theater

  - alias: Turn off Home Theater when Plex has been idle
    trigger:
      platform: state
      entity_id: media_player.greg_s_mac_mini
      to: 'idle'
      for:
        minutes: 30
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.home_theater
          state: 'on'
        - condition: template
          value_template: '{{ is_state_attr("media_player.home_theater", "source", "Watch Plex") }}'
    action:
      - service: homeassistant.turn_off
        entity_id: media_player.home_theater

  ## AUTOMATIC SPOTIFY ON TV ACTIVITIES
  - alias: Turn on Home Theater when Spotify casts to Fire TV
    trigger:
      - platform: state
        entity_id: binary_sensor.spotify_output_to_firetv
        to: 'on'
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.spotify_output_to_firetv
          state: 'on'
        - condition: state
          entity_id: media_player.home_theater
          state: 'off'
    action:
      - service: media_player.select_source
        entity_id:
          - media_player.home_theater
        data:
          source: 'Listen to Music'

  - alias: Turn off Home Theater when Spotify stops casting to Fire TV
    trigger:
      - platform: state
        entity_id: binary_sensor.spotify_output_to_firetv
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: media_player.spotify
        to: 'paused'
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.home_theater
          state: 'on'
        - condition: template
          value_template: '{{ is_state_attr("media_player.home_theater", "source", "Listen to Music") }}'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - media_player.home_theater

