sensor:
  - platform: template
    sensors:
      house_mode:
        friendly_name: 'House Mode'
        value_template: >
          {% if is_state('input_boolean.visitor_mode', 'on') %}
            visitor
          {% elif is_state('input_boolean.residents_away', 'on') %}
            away
          {% else %}
            home
          {% endif %}

input_boolean:
  residents_away:
    name: Residents Away
    initial: off
    icon: mdi:home

  visitor_mode:
    name: Visitor Mode
    initial: off
    icon: mdi:account-multiple


script:
  enable_residents_away:
    alias: Enable Away Mode
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.residents_away
      - event: LOGBOOK_ENTRY
        event_data:
          name: Residents
          message: have all left the house
          entity_id: input_boolean.residents_away
          domain: automation

automation:
  - alias: All residents have left the house
    trigger:
      platform: state
      entity_id: group.residents
      to: not_home
      for:
        minutes: 10
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.residents_away

  - alias: A resident has returned home
    trigger:
      platform: state
      entity_id: group.residents
      to: home
      for:
        minutes: 1
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.residents_away

