###########################
## Z-WAVE CORE           ##
###########################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config

homeassistant:
  customize:
    binary_sensor.aeotec_zw100_multisensor_6_sensor_2_0:
      friendly_name: Living Room Motion
    binary_sensor.aeotec_zw100_multisensor_6_sensor_4_0:
      friendly_name: Finn's Room Motion

    sensor.aeotec_zw100_multisensor_6_alarm_level_2_1:
      friendly_name: Living Room Alarm Level
    sensor.aeotec_zw100_multisensor_6_alarm_type_2_0 :
      friendly_name: Living Room Alarm Type
    sensor.aeotec_zw100_multisensor_6_burglar_2_10:
      friendly_name: Living Room Burglar
    sensor.aeotec_zw100_multisensor_6_luminance_2_3:
      friendly_name: Living Room Lux
    sensor.aeotec_zw100_multisensor_6_relative_humidity_2_5:
      friendly_name: Living Room Humidity
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_2_2:
      friendly_name: Living Room Source Node ID
    sensor.aeotec_zw100_multisensor_6_temperature_2_1:
      friendly_name: Living Room Temp
    sensor.aeotec_zw100_multisensor_6_ultraviolet_2_27:
      friendly_name: Living Room UV

    sensor.aeotec_zw100_multisensor_6_alarm_level_4_1:
      friendly_name: Finn's Room Alarm Level
    sensor.aeotec_zw100_multisensor_6_alarm_type_4_0 :
      friendly_name: Finn's Room Alarm Type
    sensor.aeotec_zw100_multisensor_6_burglar_4_10:
      friendly_name: Finn's Room Burglar
    sensor.aeotec_zw100_multisensor_6_luminance_4_3:
      friendly_name: Finn's Room Lux
    sensor.aeotec_zw100_multisensor_6_relative_humidity_4_5:
      friendly_name: Finn's Room Humidity
    sensor.aeotec_zw100_multisensor_6_sourcenodeid_4_2:
      friendly_name: Finn's Room Source Node ID
    sensor.aeotec_zw100_multisensor_6_temperature_4_1:
      friendly_name: Finn's Room Temp
    sensor.aeotec_zw100_multisensor_6_ultraviolet_4_27:
      friendly_name: Finn's Room UV

    sensor.aeotec_zw096_smart_switch_6_current_3_20:
      friendly_name: Water Boiler Current
      hidden: true
    sensor.aeotec_zw096_smart_switch_6_energy_3_0:
      friendly_name: Water Boiler Energy
    sensor.aeotec_zw096_smart_switch_6_power_3_8:
      friendly_name: Water Boiler Power
    sensor.aeotec_zw096_smart_switch_6_previous_reading_3_1:
      friendly_name: Water Boiler Previous Reading
    sensor.aeotec_zw096_smart_switch_6_voltage_3_16:
      friendly_name: Water Boiler Voltage
      hidden: true

    switch.aeotec_zw096_smart_switch_6_switch_3_0:
      friendly_name: Water Boiler
      icon: mdi:coffee
