###########################
## Z-WAVE CORE           ##
###########################

zwave:
  usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config

homeassistant:
  customize:
    binary_sensor.living_room_multisensor_sensor:
      friendly_name: Living Room Motion
      device_class: motion
    binary_sensor.finns_room_multisensor_sensor:
      friendly_name: Finn's Room Motion
      device_class: motion
    binary_sensor.bedroom_multisensor_sensor:
      friendly_name: Bedroom Motion
      device_class: motion

    sensor.living_room_multisensor_alarm_level:
      friendly_name: Living Room Alarm Level
      hidden: true
    sensor.living_room_multisensor_alarm_type :
      friendly_name: Living Room Alarm Type
      hidden: true
    sensor.living_room_multisensor_burglar:
      friendly_name: Living Room Burglar
      hidden: true
    sensor.living_room_multisensor_luminance:
      friendly_name: Living Room Lux
    sensor.living_room_multisensor_relative_humidity:
      friendly_name: Living Room Humidity
    sensor.living_room_multisensor_sourcenodeid:
      friendly_name: Living Room Source Node ID
      hidden: true
    sensor.living_room_multisensor_temperature:
      friendly_name: Living Room Temp
    sensor.living_room_multisensor_ultraviolet:
      friendly_name: Living Room UV
      hidden: true

    sensor.finns_room_multisensor_alarm_level:
      friendly_name: Finn's Room Alarm Level
      hidden: true
    sensor.finns_room_multisensor_alarm_type :
      friendly_name: Finn's Room Alarm Type
      hidden: true
    sensor.finns_room_multisensor_burglar:
      friendly_name: Finn's Room Burglar
      hidden: true
    sensor.finns_room_multisensor_luminance:
      friendly_name: Finn's Room Lux
    sensor.finns_room_multisensor_relative_humidity:
      friendly_name: Finn's Room Humidity
    sensor.finns_room_multisensor_sourcenodeid:
      friendly_name: Finn's Room Source Node ID
      hidden: true
    sensor.finns_room_multisensor_temperature:
      friendly_name: Finn's Room Temp
    sensor.finns_room_multisensor_ultraviolet:
      friendly_name: Finn's Room UV
      hidden: true

    sensor.bedroom_multisensor_alarm_level:
      friendly_name: Bedroom Alarm Level
      hidden: true
    sensor.bedroom_multisensor_alarm_type :
      friendly_name: Bedroom Alarm Type
      hidden: true
    sensor.bedroom_multisensor_burglar:
      friendly_name: Bedroom Burglar
      hidden: true
    sensor.bedroom_multisensor_luminance:
      friendly_name: Bedroom Lux
    sensor.bedroom_multisensor_relative_humidity:
      friendly_name: Bedroom Humidity
    sensor.bedroom_multisensor_sourcenodeid:
      friendly_name: Bedroom Source Node ID
      hidden: true
    sensor.bedroom_multisensor_temperature:
      friendly_name: Bedroom Temp
    sensor.bedroom_multisensor_ultraviolet:
      friendly_name: Bedroom UV
      hidden: true

    # sensor.water_boiler_switch_current:
    #   friendly_name: Water Boiler Current
    #   hidden: true
    # sensor.water_boiler_switch_energy:
    #   friendly_name: Water Boiler Energy
    #   hidden: false
    # sensor.water_boiler_switch_power:
    #   friendly_name: Water Boiler Power
    # sensor.water_boiler_switch_previous_reading:
    #   friendly_name: Water Boiler Previous Energy
    #   hidden: true
    # sensor.water_boiler_switch_previous_reading_2:
    #   friendly_name: Water Boiler Previous Power
    #   hidden: true
    # sensor.water_boiler_switch_voltage:
    #   friendly_name: Water Boiler Voltage
    #   hidden: true

    # switch.water_boiler_switch_switch:
    #   friendly_name: Water Boiler
    #   icon: mdi:coffee

    sensor.washer_switch_current:
      friendly_name: Washer Current
      hidden: true
    sensor.washer_switch_energy:
      friendly_name: Washer Energy
      hidden: true
    sensor.washer_switch_power:
      friendly_name: Washer Power
    sensor.washer_switch_previous_reading:
      friendly_name: Washer Previous Energy
      hidden: true
    sensor.washer_switch_previous_reading_2:
      friendly_name: Washer Previous Power
      hidden: true
    sensor.washer_switch_voltage:
      friendly_name: Washer Voltage
      hidden: true

    switch.washer_switch_switch:
      friendly_name: Washer
      icon: mdi:washing-machine
      hidden: true

    sensor.dryer_switch_current:
      friendly_name: Dryer Current
      hidden: true
    sensor.dryer_switch_energy:
      friendly_name: Dryer Energy
      hidden: true
    sensor.dryer_switch_power:
      friendly_name: Dryer Power
    sensor.dryer_switch_previous_reading:
      friendly_name: Dryer Previous Energy
      hidden: true
    sensor.dryer_switch_previous_reading_2:
      friendly_name: Dryer Previous Power
      hidden: true
    sensor.dryer_switch_voltage:
      friendly_name: Dryer Voltage
      hidden: true

    switch.dryer_switch_switch:
      friendly_name: Dryer
      icon: mdi:washing-machine
      hidden: true
